@startuml

title __DOMAIN's Class Diagram__\n

    namespace omain {
      class Domain.Nota {
          - data : int
          - id : Entry<String, Integer>
          - valoare : float
          + Nota()
          + getDl()
          + getID()
          + getPredat()
          + getStud()
          + getStudent()
          + getTema()
          + getVal()
          + getValoare()
          + setID()
      }
    }

  


    namespace omain {
      class Domain.Student {
          - email : String
          - grupa : int
          - idStudent : String
          - nume : String
          - profesor : String
          + Student()
          + equals()
          + getGrupa()
          + getID()
          + getMail()
          + getNume()
          + getProfesor()
          + setGrupa()
          + setID()
          + setMail()
          + setNume()
          + setProfesor()
          + toString()
      }
    }

  


    namespace omain {
      class Domain.Teme {
          - deadline : Integer
          - descriere : String
          - nr : Integer
          - sapt_primire : Integer
          + Teme()
          + getDeadline()
          + getDescriere()
          + getID()
          + getSapt_primire()
          + setDeadline()
          + setDescriere()
          + setID()
          + setSapt_primire()
          + toString()
      }
    }

  


    namespace omain {
      interface Domain.hasID {
          {abstract} + getID()
          {abstract} + setID()
      }
    }

  

  Domain.Nota .up.|> Domain.hasID
  Domain.Nota o-- Domain.Student : st
  Domain.Nota o-- Domain.Teme : tm
  Domain.Student .up.|> Domain.hasID
  Domain.Teme .up.|> Domain.hasID


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
