@startuml

title __REPOSITORY's Class Diagram__\n


    namespace epository {
      abstract class Repository.AbstractRepo {
          - repo : Map<ID, E>
          - validator : Validator<E>
          + AbstractRepo()
          + delete()
          + findAll()
          + findOne()
          + save()
          + size()
          + update()
      }
    }

  


    namespace epository {
      interface Repository.CrudRepo {
          {abstract} + delete()
          {abstract} + findAll()
          {abstract} + findOne()
          {abstract} + save()
          {abstract} + size()
          {abstract} + update()
      }
    }

  


    namespace epository {
      class Repository.NoteRepo {
          - builderFactory : DocumentBuilderFactory
          + NoteRepo()
          + save()
          - writeToFile()
          - writeToFile2()
      }
    }

  


    namespace epository {
      class Repository.StudentRepo {
          - builderFactory : DocumentBuilderFactory
          - fName : String
          + StudentRepo()
          + delete()
          + loadFromFile()
          + save()
          + update()
          - writeToFile()
      }
    }

  


    namespace epository {
      class Repository.TemeRepo {
          - builderFactory : DocumentBuilderFactory
          - fName : String
          + TemeRepo()
          + delete()
          + loadFromFile()
          + save()
          + update()
          - writeToFile()
      }
    }

  

  Repository.AbstractRepo .up.|> Repository.CrudRepo
  Repository.NoteRepo -up-|> Repository.AbstractRepo
  Repository.StudentRepo -up-|> Repository.AbstractRepo
  Repository.TemeRepo -up-|> Repository.AbstractRepo


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
